# Generated by Django 3.1.6 on 2021-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.CharField(max_length=150, verbose_name='ID-участника')),
                ('mName', models.CharField(max_length=50, verbose_name='USERNAME-участника')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
