# Generated by Django 3.1.6 on 2021-05-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(allow_unicode=True, default='', editable=False),
        ),
    ]
