# Generated by Django 3.1.6 on 2021-05-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_shop', '0002_auto_20210508_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
