# Generated by Django 3.1.6 on 2021-05-08 19:09

import big_shop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('big_shop', '0003_auto_20210508_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=-2, upload_to='photo_archive/category/<django.db.models.fields.SlugField>'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Продукт')),
                ('price', models.FloatField(default=1.0, verbose_name='Цена')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('image', models.ImageField(upload_to=big_shop.models.get_product_image_path)),
                ('product_slug', models.SlugField(default='', editable=False)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='big_shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
