# Generated by Django 3.1.6 on 2021-05-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_shop', '0004_auto_20210508_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='photo_archive/category/'),
        ),
    ]
